name: graduation_project
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  animated_splash_screen: ^1.3.0
  awesome_dialog: ^3.2.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.3
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_gemini: ^3.0.0
  firebase_storage: ^12.4.5
  firebase_database: ^11.3.5
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.1.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  google_generative_ai: ^0.4.6
  google_sign_in: ^6.2.2
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  latlong2: ^0.9.1
  location: ^8.0.0
  permission_handler: ^11.3.1
  salomon_bottom_bar: ^3.3.2
  shared_preferences:
  smooth_page_indicator: ^1.2.0+3
  intl_utils: ^2.8.10
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.4
  lottie: ^3.3.1
  cached_network_image: ^3.4.1
  flutter_map_tile_caching: ^10.1.0
  dio: ^5.8.0+1
  syncfusion_flutter_charts: ^29.1.37+1
  shimmer: ^3.0.0
  get_it: ^8.0.3
  equatable: ^2.0.5
flutter_native_splash:
  color: "#FFF5E6"
  image: assets/images/logo.png
  android: true
  ios: true

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/animations/
  #   - images/a_dot_ham.jpeg
flutter_intl:
  enabled: true
